base: [../ssda/synthia2cityscapes.yaml]
output_dir: outputs/road/vfm/ssda_rdkc/synthia2cityscapes_1_64
data:
  target_labeled:
    split: splits/road/cityscapes/rdkc_s2c/1_64/labeled.txt
  target_unlabeled:
    split: splits/road/cityscapes/rdkc_s2c/1_64/unlabeled.txt
